output:
  folder: output/figure2/u10_sgd
  target_model_count: 50000
dataset:
  name: kink
  kink:
    margin: 0.25
    noise: 0
model:
  arch: mlp
  mlp:
    hidden_units: 10
    layers: 1
  model_count_times_batch_size: 4800000
  init: regular
optimizer:
  name: SGD
  lr: 0.1
  epochs: 200
  batch_size: 3
distributed:
  loss_thres: "-999,999"
  data_seed: 0
  training_seed: 0
  target_model_count_subrun: 50000
  num_samples: "16"