name: optimizer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - pytorch=1.10.2
  - torchvision=0.11.3
  - pip=21.2.4
  - matplotlib=3.5.1
  - scipy=1.7.3
  - pip:
    - tabulate==0.9.0
    - tqdm==4.62.3
    - terminaltables==3.1.10
    - fastargs==1.2.0
    - pyyaml==6.0

