output:
  folder: output/table4/cifar_patternfast
  target_model_count: 100
dataset:
  name: cifar10
  mnistcifar:
    num_classes: 10
model:
  arch: lenet
  lenet:
    width: 1
  model_count_times_batch_size: 50000
optimizer:
  name: PatternSearchFast
  epochs: 80000
  es_acc: 1
distributed:
  loss_thres: -999,999
  num_samples: 100,300,500,1000