output:
  folder: output/table4/mnist_greedyrandom
  target_model_count: 100
dataset:
  name: mnist
  mnistcifar:
    num_classes: 10
model:
  arch: lenet
  lenet:
    width: 1
  model_count_times_batch_size: 200000
optimizer:
  name: GreedyRandom
  epochs: 80000
  es_acc: 1
distributed:
  loss_thres: -999,999
  num_samples: 100,300,500,1000
