output:
  folder: output/table2/mnist_sgd
  target_model_count: 200
dataset:
  name: mnist
  seed: 100
  mnistcifar:
    num_classes: 2
model:
  arch: lenet
  lenet:
    width: 0.5
  model_count_times_batch_size: 3000
optimizer:
  name: SGD
  lr: 0.001
  epochs: 30
  batch_size: 2
training:
  seed: 0
distributed:
  loss_thres: 0.3,0.35,0.4,0.45,0.5,0.55,0.6,0.65
  num_samples: 2,4,8,16,32
  target_model_count_subrun: 20