python train_distributed.py --config configs/figure2/guess_u2.yaml
python train_distributed.py --config configs/figure2/guess_u4.yaml
python train_distributed.py --config configs/figure2/guess_u6.yaml
python train_distributed.py --config configs/figure2/guess_u8.yaml
python train_distributed.py --config configs/figure2/guess_u10.yaml
python train_distributed.py --config configs/figure2/guess_u15.yaml 
python train_distributed.py --config configs/figure2/guess_u20.yaml
python train_distributed.py --config configs/figure2/sgd_u2.yaml
python train_distributed.py --config configs/figure2/sgd_u4.yaml
python train_distributed.py --config configs/figure2/sgd_u6.yaml
python train_distributed.py --config configs/figure2/sgd_u8.yaml
python train_distributed.py --config configs/figure2/sgd_u10.yaml
python train_distributed.py --config configs/figure2/sgd_u15.yaml 
python train_distributed.py --config configs/figure2/sgd_u20.yaml